export const LANDMARKS: Record<string, string> = {
  KLCC: "klcc",
  "Petronas Tower": "klcc",
  "Pavilion KL": "klcc",
  "Bukit Bintang": "klcc",
  "Menara TM": "klcc",
  "Masjid Jamek": "klcc",
  "Chow Kit LRT": "klcc",
  Titiwangsa: "klcc",
  "Mid Valley": "bangsar",
  "The Gardens": "bangsar",
  "KL Sentral": "bangsar",
  "Bangsar Village": "bangsar",
  "1 Utama": "mont-kiara",
  Publika: "mont-kiara",
  "HELP University": "mont-kiara",
  Hartamas: "sri-hartamas",
  "Sunway Pyramid": "subang-jaya",
  "Sunway University": "subang-jaya",
  "Taylor's University": "subang-jaya",
  SS15: "subang-jaya",
  USJ: "subang-jaya",
  "Asia Jaya LRT": "petaling-jaya",
  "Kelana Jaya LRT": "petaling-jaya",
  "PJ Old Town": "petaling-jaya",
  UM: "petaling-jaya",
  UPM: "petaling-jaya",
  "Pavilion Bukit Jalil": "bukit-jalil",
  "Stadium Nasional": "bukit-jalil",
  "IOI City Mall": "putrajaya",
  "Damansara Perdana": "damansara",
};
